// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkEoMb4S919PMEZOmpB4I53THCx_hniis',
    appId: '1:735267924813:web:a275d7f1ee78d5e5e92504',
    messagingSenderId: '735267924813',
    projectId: 'plants-project-46e01',
    authDomain: 'plants-project-46e01.firebaseapp.com',
    storageBucket: 'plants-project-46e01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXnsrTdUPn9eBxvYFVLX2Lgl4rKL0GeKA',
    appId: '1:735267924813:android:8af6c33be58bd3c1e92504',
    messagingSenderId: '735267924813',
    projectId: 'plants-project-46e01',
    storageBucket: 'plants-project-46e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91vNTr6LW1s_p69VQYMMoC2KQ4jYEhFU',
    appId: '1:735267924813:ios:5deb632515ec0fabe92504',
    messagingSenderId: '735267924813',
    projectId: 'plants-project-46e01',
    storageBucket: 'plants-project-46e01.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );
}
